config/routes.rb
Rails.application.routes.draw do
  root "tops#index"
  resources :tops, only: [:index, :show]
  post "tops" => "tops#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area_code.rb
class AreaCode < ApplicationRecord
    belongs_to :pref_code, foreign_key: "pref_id"
end

app/models/pref_code.rb
class PrefCode < ApplicationRecord
    has_many :area_codes, foreign_key: "pref_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
    require 'uri'
    require 'net/http'
    require 'json'
    require 'rexml/document'

    USER_AGENT = "TestAppForMyPortfolio".freeze

    def index
        @pref_list = PrefCode.all.order('id')
        req_city_code = params['city']
        
        if req_city_code.present?
            uri = "https://weather.tsukumijima.net/api/forecast/city/#{req_city_code}"
            uri = URI.parse(uri)
            http = Net::HTTP.new(uri.host, uri.port)
            http.use_ssl = uri.scheme === "https"
            response = http.get(uri.path, 'User-Agent': USER_AGENT)
            @res = JSON.parse(response.body)

        end

        sleep 1
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- bootstrapの読み込み -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <!-- jQueryの読み込み -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row">
      <header>
      </header>
    </div>
    <div class="row">
      <%= yield %>
    </div>
    <!-- bootstrapの読み込み -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tops/index.html.erb
<h1 class="display-6">お天気情報</h1>
<div class="container">
    <div>
        <%= form_with url: tops_path, local: true, method: 'post' do |form| %>
            <div class="row m-2 g-3">
                <div class="col-sm-3">
                    <%= form.collection_select :pref, @pref_list, :pref_id, :pref_name, {"prompt": "都道府県を選択"}, {id: 'pref', class: 'form-select'} %>
                </div>
                <div class="col-sm-3">
                    <div id="city_list_insert_point"></div>

                    <div id="city_dummy">
                        <%= form.select :city, ['---'], {}, {id: 'city_dummy', class: 'form-select'} %>
                    </div>
                </div>
                <div class="col">
                    <%= form.submit "取得", class: "btn btn-primary" %>
                </div>
            </div>


            <% @pref_list.each do |pref| %>
                <template id="city_<%= pref.pref_id %>">
                    <div id="selected_city">
                        <%= form.collection_select :city, pref.area_codes, :city_id, :city_name, {"prompt": "市町村を選択"}, {id: 'city', class: 'form-select'} %>
                    </div>
                </template>
            <% end %>
        <% end %>
    </div>


    <div class="mt-4">
        <table class="table">
            <% if @res %>
                <p class="fs-4"><%= @res['title'] %></p>
                <thead>
                    <tr>
                        <th>日時</th>
                        <th>天気</th>
                        <th>最低気温（℃）</th>
                        <th>最高気温（℃）</th>
                    </tr>
                </thead>
                <tbody>
                    <% for i in 0..2 do %>
                        <% require 'date' %>
                        <tr>
                            <td><%= Date.parse(@res['forecasts'][i]['date']).strftime("%Y年%m月%d日") %></td>
                            <td><%= @res['forecasts'][i]['telop'] %></td>
                            <td><%= @res['forecasts'][i]['temperature']['min']['celsius'] %></td>
                            <td><%= @res['forecasts'][i]['temperature']['max']['celsius'] %></td>
                        </tr>
                    <% end %>
                </tbody>
            <% end %>
        </table>
    </div>
    
    <p class="small">
        天気情報は<a href="https://weather.tsukumijima.net/">天気予報API様</a>よりデータを取得させていただいております。
    <p>

</div>